template = "https://github.com/giellalt/template-lang-und"
rev_id = 259
template_sha = "dbafdbc00bdeb17f80ec54b2fd5d6ae330f25f51"

[replacements]
__GLOTTOLOG_ID__ = "ndol1238"
__REPO__ = "lang-ndl"
__UND2C__ = "ndl"
__UNDEFINED__ = "Ndolo"
__UND__ = "ndl"
