template = "https://github.com/giellalt/template-lang-und"
rev_id = 266
template_sha = "0bf1857d37e3d9d859c2f97c9772ed27d291955c"

[replacements]
__GLOTTOLOG_ID__ = "ndol1238"
__REPO__ = "lang-ndl"
__UND2C__ = "ndl"
__UNDEFINED__ = "Ndolo"
__UND__ = "ndl"
